### ISSUE TITLE
Пакет отсутствует на Packagist

### ISSUE THREAD

**Issue by slruslan** [antonmarin/amocrm#1]
Доброго времени суток :)
Антон, нет желания разместить пакет на packagist.com?
Сейчас его не очень удобно подключать к проекту.

Был бы благодарен.

**Comment by antonmarin** [comment]
Добавлю как только закончу ))

01.03.2016, 22:38, "Ruslan Slinkov" <notifications@github.com>:

**Comment by antonmarin** [comment]
https://packagist.org/packages/antonmarin/amocrm
Пока добавил.
